spring:
#  profiles:
#    active: local
#    group:
#      local: local, common
#      prod: prod, common
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    redis:
      host: ${REDIS_ENDPOINT}
      port: 6379
  jpa:
    defer-datasource-initialization: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 500
      format_sql: true
      naming:
        physical-strategy: prgrms.project.stuti.global.config.SnakeUpperCaseNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB

  security:
    # URI ignore or permit-all
    patterns:
      permitAll: [ ]
      member:
        GET: [ ]
        POST: [ ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
    # Security OAuth
    oauth2:
      client:
        registration:
          naver:
            client-id: ZJzO1vImgGzN2XHQZ__F
            client-secret: mxnBPNlucz
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: [ name, email, profile_image ]
          google:
            client-id: 941480679229-7seu3agto0jlhnuq0hv6v4vj11eoqf5r.apps.googleusercontent.com
            client-secret: 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
            scope: [ profile, email ]
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:sql/migration, classpath:db/data
#    enabled: false
#    enabled: true
#    baseline-on-migrate: true
app:
  jwt:
    header: token
    issuer: prgrms
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 3000000000
    refreshTokenExpiry: 7776000000
  # cors
  cors:
    allowed-origins: 'http://localhost:3000'
    allowed-methods: GET,POST,PUT,PATCH,DELETE
    allowed-headers: '*'
    max-age: 3600
  # OAuth path
  oauth:
    domain: "http://localhost:3000"
    signupPath: "/signup"
    signupTime: 300
    loginSuccessPath: "/main"

# Sentry
DSN: https://e6ac8fba443a46ea8425aadf84c6325c@o1332931.ingest.sentry.io/6597826
